# Replace with http_archive if using outside of this repository:
# see https://github.com/tweag/rules_nixpkgs/#setup
#
# You will need to add the load() for the http_archive rule itself, followed
# by an http_archive() pointing to a specific commit or tag.
#
# As an example, for a release tag, you may want something like:
#
# load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
# http_archive(
#     name = "io_tweag_rules_nixpkgs",
#     strip_prefix = "rules_nixpkgs-X.Y.Z",
#     urls = ["https://github.com/tweag/rules_nixpkgs/archive/refs/tags/vX.Y.Z.tar.gz"],
#     # this is optional
#     sha256 = "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
# )

local_repository(
    name = "io_tweag_rules_nixpkgs",
    path = "../../../",
)

load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")
# load everything that rules_nixpkgs rules need to work
rules_nixpkgs_dependencies()

load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_local_repository", "nixpkgs_cc_configure")
nixpkgs_local_repository(
    name = "nixpkgs",
    nix_file = "//:nixpkgs.nix",
    nix_file_deps = ["//:flake.lock"],
)

nixpkgs_cc_configure(
  repository = "@nixpkgs",
  name = "nixpkgs_config_cc",
)

# load rules_cc
http_archive(
    name = "rules_cc",
    sha256 = "4dccbfd22c0def164c8f47458bd50e0c7148f3d92002cdb459c2a96a68498241",
    urls = ["https://github.com/bazelbuild/rules_cc/releases/download/0.0.1/rules_cc-0.0.1.tar.gz"],
)
load("@rules_cc//cc:repositories.bzl", "rules_cc_dependencies", "rules_cc_toolchains")
rules_cc_dependencies()
rules_cc_toolchains()
