# Replace the local_repository call below with http_archive if using this
# outside of this repository as a template for your own project:
# see https://github.com/tweag/rules_nixpkgs/#setup
#
# You will need a load() for the http_archive rule itself, followed
# by an http_archive() pointing to a specific commit or tag.
#
# As an example, for a release tag X.Y.Z, you may want something like:
#
# load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
# http_archive(
#     name = "io_tweag_rules_nixpkgs",
#     strip_prefix = "rules_nixpkgs-X.Y.Z",
#     urls = ["https://github.com/tweag/rules_nixpkgs/archive/refs/tags/vX.Y.Z.tar.gz"],
#     # this is optional but recommended
#     # to find the hash for the release/commit you picked, you can leave this
#     # as-is and run `bazel run`, which will mention the correct hash in the
#     # error message
#     sha256 = "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
# )

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
local_repository(
    name = "io_tweag_rules_nixpkgs",
    path = "../../",
)

load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")
# load everything that rules_nixpkgs rules need to work
rules_nixpkgs_dependencies()

load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_local_repository", "nixpkgs_cc_configure")
nixpkgs_local_repository(
    name = "nixpkgs",
    nix_file = "//:nixpkgs.nix",
    nix_file_deps = ["//:flake.lock"],
)

nixpkgs_cc_configure(
  repository = "@nixpkgs",
  name = "nixpkgs_config_cc",
)

# load rules_cc
http_archive(
    name = "rules_cc",
    sha256 = "2037875b9a4456dce4a79d112a8ae885bbc4aad968e6587dca6e64f3a0900cdf",
    urls = ["https://github.com/bazelbuild/rules_cc/releases/download/0.0.9/rules_cc-0.0.9.tar.gz"],
)
load("@rules_cc//cc:repositories.bzl", "rules_cc_dependencies", "rules_cc_toolchains")
rules_cc_dependencies()
rules_cc_toolchains()
