queue_rules:
  - name: default
    queue_conditions:
      - base=master
      - check-success~=Build & Test - Nixpkgs - .*
      - check-success~=Build & Test - Examples \(.*\)
      - "#approved-reviews-by>=1"
      - "label=merge-queue"
    merge_conditions:
      - check-success~=Build & Test - Nixpkgs - .*
      - check-success~=Build & Test - Examples \(.*\)
    merge_method: merge

pull_request_rules:
  - name: remove from merge-queue after merge
    conditions:
      - merged
    actions:
      label:
        remove:
          - "merge-queue"
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
