# Replace with http_archive: https://github.com/tweag/rules_nixpkgs/#setup
local_repository(
    name = "io_tweag_rules_nixpkgs",
    path = "../../../"
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
revision = "dc66c1612b7a3e96531eff22136570124c8eec81"
http_archive(
    name = "rules_rust",
    sha256 = "9dadbcd1136f7d4f3f2e7c0790531be0fdcccc535dec42a4c5a6f2df7380e3e3",
    strip_prefix = "rules_rust-{}".format(revision),
    urls = [
        # `main` branch as of 2021-12-01
        "https://github.com/bazelbuild/rules_rust/archive/{}.tar.gz".format(revision),
    ],
)

load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")
rules_nixpkgs_dependencies()

load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_git_repository")
nixpkgs_git_repository(
    name = "nixpkgs",
    revision = "21.11",
    sha256 = "c77bb41cf5dd82f4718fa789d49363f512bb6fa6bc25f8d60902fe2d698ed7cc",
)

load("@io_tweag_rules_nixpkgs//nixpkgs:toolchains/rust.bzl", "nixpkgs_rust_configure")
nixpkgs_rust_configure(
    repository = "@nixpkgs//:default.nix",
    fail_not_supported = False,
    sdk_name = "nix_rust",
)

load("@rules_rust//rust:repositories.bzl", "rust_repositories")
rust_repositories()
