# Replace with http_archive: https://github.com/tweag/rules_nixpkgs/#setup
local_repository(
    name = "io_tweag_rules_nixpkgs",
    path = "../../../",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")

rules_nixpkgs_dependencies()

load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_git_repository")

nixpkgs_git_repository(
    name = "nixpkgs",
    # branch nixos-25.05
    revision = "ac62194c3917d5f474c1a844b6fd6da2db95077d",
    sha256 = "bf13a5324bc541eeda82fb97a80ba6326acc4fa91d6bac8f78fb309ce4a31e37",
)

load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_cc_configure", "nixpkgs_python_configure")

nixpkgs_cc_configure(
    repository = "@nixpkgs",
)

nixpkgs_python_configure(
    python3_attribute_path = "python3.withPackages(ps: with ps; [ numpy opencv4 ])",
    repository = "@nixpkgs",
)
