module(
    name = "rules_nixpkgs_core",
    version = "0.14.0",
)

bazel_dep(name = "platforms", version = "0.0.9")
bazel_dep(name = "bazel_features", version = "1.36.0")
bazel_dep(name = "bazel_skylib", version = "1.6.1")
bazel_dep(name = "rules_license", version = "1.0.0")

nix_repo = use_extension("//extensions:repository.bzl", "nix_repo")
nix_repo.github(
    name = "nixpkgs",
    tag = "25.05",
    sha256 = "130b4257b3d53bfbfea6d61fb76d4751a3989a4a09a28615ff77516a82b3924d",
)
use_repo(nix_repo, "nixpkgs")
