workspace(name = "rules_nixpkgs_python_testing")

local_repository(
    name = "rules_nixpkgs_python",
    path = "../../toolchains/python",
)

load(
    "//tests:nixpkgs_repositories.bzl",
    "nixpkgs_repositories",
)

nixpkgs_repositories(bzlmod = False)
