workspace(name = "rules_nixpkgs_nodejs_testing")

local_repository(
    name = "rules_nixpkgs_nodejs",
    path = "..",
)

local_repository(
    name = "rules_nixpkgs_core",
    path = "../../../core",
)

local_repository(
    name = "rules_nixpkgs_cc",
    path = "../../cc",
)

local_repository(
    name = "rules_nixpkgs_java",
    path = "../../java",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "83d2bb029c2a9a06a474c8748d1221a92a7ca02222dcf49a0b567825c4e3f1ce",
    strip_prefix = "rules_nodejs-6.3.0",
    urls = ["https://github.com/bazel-contrib/rules_nodejs/releases/download/v6.3.0/rules_nodejs-v6.3.0.tar.gz"],
)

load("@build_bazel_rules_nodejs//:repositories.bzl", "build_bazel_rules_nodejs_dependencies")

build_bazel_rules_nodejs_dependencies()

http_archive(
    name = "bazel_skylib",
    sha256 = "bc283cdfcd526a52c3201279cda4bc298652efa898b10b4db0837dc51652756f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.7.1/bazel-skylib-1.7.1.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.7.1/bazel-skylib-1.7.1.tar.gz",
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

load(
    "//tests:nixpkgs_repositories.bzl",
    "nixpkgs_repositories",
)

nixpkgs_repositories(bzlmod = False)
