def _external_workspace_impl(repository_ctx):
    build = '''\
load("@nixpkgs_packages//:defs.bzl", "get_pkg")

genrule(
    name = "generated",
    srcs = [get_pkg("transitive", "1.1.3", "tool", "package")],
    outs = ["generated.out"],
    cmd = """\\
echo 'generated by transitive 1.1.3 in external_workspace with' > $(OUTS)
cat $(SRCS) >> $(OUTS)
""",
    visibility = ["//visibility:public"],
)
'''
    repository_ctx.file("BUILD.bazel", build, executable = False)

_external_workspace = repository_rule(_external_workspace_impl)

def _non_module_deps_impl(module_ctx):
    _external_workspace(name = "external_workspace")

non_module_deps = module_extension(_non_module_deps_impl)
