workspace(name = "rules_nixpkgs_java_testing")

local_repository(
    name = "rules_nixpkgs_java",
    path = "../../toolchains/java",
)

local_repository(
    name = "rules_nixpkgs_cc",
    path = "../../toolchains/cc",
)

local_repository(
    name = "rules_nixpkgs_core",
    path = "../../core",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_skylib",
    sha256 = "3b5b49006181f5f8ff626ef8ddceaa95e9bb8ad294f7b5d7b11ea9f7ddaf8c59",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.9.0/bazel-skylib-1.9.0.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.9.0/bazel-skylib-1.9.0.tar.gz",
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

load(
    "//tests:nixpkgs_repositories.bzl",
    "nixpkgs_repositories",
)

nixpkgs_repositories(bzlmod = False)
