# NOTE: temporary boilerplate for compatibility with `WORKSPACE` setup!
# TODO: remove when migration to `bzlmod` is complete

### generic dependencies for rendering documentation

local_repository(
    name = "io_tweag_rules_nixpkgs",
    path = "../..",
)

local_repository(
    name = "rules_nixpkgs_docs",
    path = "../../docs",
)

load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")

rules_nixpkgs_dependencies()

load("@rules_nixpkgs_docs//:dependencies_1.bzl", "docs_dependencies_1")

docs_dependencies_1()

load("@rules_nixpkgs_docs//:dependencies_2.bzl", "docs_dependencies_2")

docs_dependencies_2()

### end generic dependencies for rendering documentation

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_nodejs",
    sha256 = "83d2bb029c2a9a06a474c8748d1221a92a7ca02222dcf49a0b567825c4e3f1ce",
    strip_prefix = "rules_nodejs-6.3.0",
    urls = ["https://github.com/bazel-contrib/rules_nodejs/releases/download/v6.3.0/rules_nodejs-v6.3.0.tar.gz"],
)

load("//:nodejs.bzl", "nixpkgs_nodejs_configure")

nixpkgs_nodejs_configure(repository = "@nixpkgs")
