workspace(name = "rules_nixpkgs_rust_testing")

local_repository(
    name = "rules_nixpkgs_rust",
    path = "../../toolchains/rust",
)

local_repository(
    name = "rules_nixpkgs_core",
    path = "../../core",
)

local_repository(
    name = "rules_nixpkgs_cc",
    path = "../../toolchains/cc",
)

local_repository(
    name = "rules_nixpkgs_java",
    path = "../../toolchains/java",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_skylib",
    sha256 = "9f38886a40548c6e96c106b752f242130ee11aaa068a56ba7e56f4511f33e4f2",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.6.1/bazel-skylib-1.6.1.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.6.1/bazel-skylib-1.6.1.tar.gz",
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

http_archive(
    name = "rules_rust",
    sha256 = "d21c328b21f3c9ecfa4c1e92dd61ace63ff22603234067cf0fe495f75ac251ae",
    urls = [
        "https://github.com/bazelbuild/rules_rust/releases/download/0.35.0/rules_rust-v0.35.0.tar.gz"
    ],
)

load("@rules_rust//rust:repositories.bzl", "rules_rust_dependencies", "rust_register_toolchains")

rules_rust_dependencies()

load(
    "//tests:nixpkgs_repositories.bzl",
    "nixpkgs_repositories",
)

nixpkgs_repositories(bzlmod = False)
