workspace(name = "rules_nixpkgs_rust_testing")

local_repository(
    name = "rules_nixpkgs_rust",
    path = "../../toolchains/rust",
)

local_repository(
    name = "rules_nixpkgs_core",
    path = "../../core",
)

local_repository(
    name = "rules_nixpkgs_cc",
    path = "../../toolchains/cc",
)

local_repository(
    name = "rules_nixpkgs_java",
    path = "../../toolchains/java",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_skylib",
    sha256 = "3b5b49006181f5f8ff626ef8ddceaa95e9bb8ad294f7b5d7b11ea9f7ddaf8c59",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.9.0/bazel-skylib-1.9.0.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.9.0/bazel-skylib-1.9.0.tar.gz",
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

http_archive(
    name = "rules_rust",
    sha256 = "5ffd9ff1f6f2f14f2057b7cbaa91a5e6acd9a4cbded5ac81dad9beb36859601e",
    urls = [
        "https://github.com/bazelbuild/rules_rust/releases/download/0.70.0/rules_rust-0.70.0.tar.gz"
    ],
)

load("@rules_rust//rust:repositories.bzl", "rules_rust_dependencies", "rust_register_toolchains")

rules_rust_dependencies()

load(
    "//tests:nixpkgs_repositories.bzl",
    "nixpkgs_repositories",
)

nixpkgs_repositories(bzlmod = False)
