workspace(name = "foo")

local_repository(
    name = "io_tweag_rules_nixpkgs",
    path = "..",
)

load(
    "@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl",
    "nixpkgs_package",
)

nixpkgs_package(
    name = "toolchain_variables",
    attribute_path = "toolchain_variables",
    build_file_content = """
# That's not //:variable.bzl, that's
# @toolchain_variables//:variables.bzl and it contains the list of
# toolchain paths.
exports_files(["variables.bzl"])
""",
    nix_file_deps = [],
    repositories = {"nixpkgs": "//:default.nix"},
)
