workspace(name = "rules_nixpkgs_cc_testing")

local_repository(
    name = "rules_nixpkgs_cc",
    path = "../../toolchains/cc",
)

load(
    "//tests:nixpkgs_repositories.bzl",
    "nixpkgs_repositories",
)

nixpkgs_repositories(bzlmod = False)
