workspace(name = "bazel-nix-python-container")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

######################
# Tweag Nix Support
######################

# Replace with http_archive: https://github.com/tweag/rules_nixpkgs/#setup
local_repository(
    name = "io_tweag_rules_nixpkgs",
    path = "../../",
)

load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")
rules_nixpkgs_dependencies()

# Define nixpkgs version
load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_git_repository")
nixpkgs_git_repository(
    name = "nixpkgs",
    revision = "22.05",
    sha256 = "0f8c25433a6611fa5664797cd049c80faefec91575718794c701f3b033f2db01",
)

# Configure the C++ toolchain
load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_cc_configure")
nixpkgs_cc_configure(
    repository = "@nixpkgs",
    exec_constraints = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
        "@io_bazel_rules_docker//platforms:run_in_container",
    ],
    target_constraints = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
)

# Configure python
load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_python_configure")
nixpkgs_python_configure(
    python3_attribute_path = "python39.withPackages(ps: [ ps.flask ])",
    repository = "@nixpkgs",
)

#########
# Docker
#########
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "b1e80761a8a8243d03ebca8845e9cc1ba6c82ce7c5179ce2b295cd36f7e394bf",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.25.0/rules_docker-v0.25.0.tar.gz"],
)

load("@io_bazel_rules_docker//repositories:repositories.bzl", container_repositories = "repositories",)
container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")
container_deps()

load("@io_bazel_rules_docker//repositories:py_repositories.bzl", "py_deps")
py_deps()

load("@io_bazel_rules_docker//python3:image.bzl", py3_image_repos = "repositories")
py3_image_repos()

load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_package")
nixpkgs_package(
    name = "raw_python39_base_image",
    build_file_content = """
package(default_visibility = [ "//visibility:public" ])
exports_files(["image"])
    """,
    nix_file = "//:python39_base_image.nix",
    repository = "@nixpkgs//:default.nix",
)

load("@io_bazel_rules_docker//container:container.bzl", "container_load" )
container_load(name = "python39_base_image", file = "@raw_python39_base_image//:image")

register_execution_platforms(
    "@io_tweag_rules_nixpkgs//nixpkgs/platforms:host",
    "@//:nix_container_platform",
)
