name: Publish to Bazel Central Registry (BCR)
on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
    secrets:
      publish_token:
        required: true

  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Name of the tag to release (e.g. v0.11.0)'
        required: true
        type: string

jobs:
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v1.5.0
    with:
      tag_name: ${{ inputs.tag_name || github.ref_name }}
      registry_fork: tweag/bazel-central-registry
      attest: false
      draft: false
    permissions:
      attestations: write
      contents: write
      id-token: write
    secrets:
      publish_token: ${{ secrets.publish_token || secrets.BCR_PUBLISH_TOKEN }}
